[Service]
ExecStartPre=/usr/bin/python3 /storage/.config/aurora6s-wake/runtime.py pre
ExecStartPost=/usr/bin/python3 /storage/.config/aurora6s-wake/runtime.py post
ExecStopPost=/usr/bin/python3 /storage/.config/aurora6s-wake/runtime.py restore
